### ISSUE TITLE
Message content not making it through

### ISSUE THREAD

**Issue by Joshfindit** [ont/slacker#7]
## Specs
Running image id `7dbf7678e365` (0.0.4)

### docker-compose.yml
```
ont_slacker:
    container_name: ont_slacker
    image: ontrif/slacker:0.0.4
    restart: unless-stopped
    ports:
      - 127.0.0.1:8025:8025
    volumes:
      - ./ont_slacker/config/config.yml:/etc/slacker/config.yml
```

### config.yml
```
default:
    channel: '#unifi-gateway'
    username: 'ont_slacker: SMTP'
    icon_url: ''
    slack_token: xoxp-
    debug: true
```

## Docker logs
```
ont_slacker    | {'from': 'UniFi Controller <>', 'to': '', 'subject': '[UniFi] Alert: UniFi Switch Disconnected (2)', 'body': [<email.message.Message object at 0x7fd2db5d3b00>, <email.message.Message object at 0x7fd2db5d3e48>]}
ont_slacker    | matched {'channel': '#unifi-gateway', 'username': 'ont_slacker: SMTP', 'icon_url': '', 'slack_token': 'xoxp-', 'debug': False}
ont_slacker    | sending to slack [<email.message.Message object at 0x7fd2db5d3b00>, <email.message.Message object at 0x7fd2db5d3e48>] {'channel': '#unifi-gateway', 'username': 'ont_slacker: SMTP', 'icon_url': '', 'slack_token': 'xoxp-', 'debug': False}
```

## Slack result 
![image](https://user-images.githubusercontent.com/1937155/69551914-e53f2d80-0f73-11ea-852d-e1de2c0745b1.png)
